name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        shell: bash
        run: |

          # NOTE: the deploy key below is per repo so it wouldn't work for the necessary submodules.
          # NOTE: this works because the submodules are public.
          git config --global url."https://github.com/".insteadOf "git@github.com:"

          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1

          # NOTE: we need to revert this because the "Deploy" step needs to use ssh
          git config --global --unset-all url."https://github.com/".insteadof
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.1
        with:
          hugo-version: '0.62.2'
          extended: true
      - name: Hugo build
        run: hugo
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: public