name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.1
        with:
          hugo-version: '0.62.2'
          extended: true
      - name: Hugo build
        run: hugo
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: public
